# -*- coding: utf-8 -*-
"""Python 102 - Assignment 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5eUBk8X6kGEtEiEFuzqIjIC0VdXNMZs
"""

class Employee:
  def __init__(self, name, number):
    self.name = name
    self.number = number
  def __repr__(self):
    return f"(name: {self.name}) (number: {self.number})"
  def __str__(self):
    return "Employee Name: " + self.name + "\nEmployee Number: " + self.number

class ProductionWorker(Employee):
  def __init__(self, name, number, shift_number, hourly_pay):
    super().__init__(name, number)
    self.shift_number = shift_number
    self.hourly_pay = hourly_pay
  def __repr__(self):
    return f"(name: {self.name}) (number: {self.number}) (shift_number: {self.shift_number}) (hourly_pay: {self.hourly_pay})"
  def __str__(self):
    return "Employee Name: " + self.name + "\nEmployee ID: " + str(self.number) + "\nEmployee Shift: " + str(self.shift_number) + "\nEmployee Hourly Pay: " + str(self.hourly_pay)

class ShiftSupervisor(Employee):
  def __init__(self, name, number, annual_salary, annual_bonus):
    super().__init__(name, number)
    self.annual_salary = annual_salary
    self.annual_bonus = annual_bonus
  def __repr__(self):
    return f"(name: {self.name}) (number: {self.number}) (annual_salary: {self.annual_salary}) (annual_bonus: {self.annual_bonus})"
  def __str__(self):
    return "Employee Name: " + self.name + "\nEmployee ID: " + str(self.number) + "\nEmployee Salary: " + str(self.shift_number) + "\nEmployee Bonus: " + str(self.annual_bonus)